# Generated by Django 5.2.1 on 2025-06-02 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_callsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='is_paid_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='callsession',
            name='price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total price for the call session.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='callsession',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='callsession',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('pending_acceptance', 'Pending Acceptance'), ('active', 'Active'), ('completed', 'Completed'), ('declined', 'Declined'), ('missed', 'Missed'), ('payment_failed', 'Payment Failed'), ('cancelled', 'Cancelled')], default='pending_acceptance', max_length=20),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_onboarding_complete', models.BooleanField(default=False)),
                ('call_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Price per call session. Define your currency unit elsewhere (e.g., USD).', max_digits=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
