# Generated by Django 5.2.1 on 2025-06-02 15:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('upload_timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the video was uploaded.')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for discoverability and content categorization.', max_length=255)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-upload_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserVideoInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_time_seconds', models.PositiveIntegerField(default=0, help_text='Total seconds the user has watched this video.')),
                ('liked', models.BooleanField(blank=True, default=None, help_text='Did the user like the video? Null means no explicit like/dislike.', null=True)),
                ('shared', models.BooleanField(default=False, help_text='Did the user share this video?')),
                ('completed_watch', models.BooleanField(default=False, help_text='Did the user watch a significant portion (e.g., >80%) of the video?')),
                ('interaction_timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of the last interaction.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_interactions', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='recommender.video')),
            ],
            options={
                'verbose_name': 'User Video Interaction',
                'verbose_name_plural': 'User Video Interactions',
                'ordering': ['-interaction_timestamp'],
                'unique_together': {('user', 'video')},
            },
        ),
    ]
