# Generated by Django 5.2.1 on 2025-06-04 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_postlike'),
        ('recommender', '0002_video_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='source_post',
            field=models.OneToOneField(blank=True, help_text='Link to the Post object if this video was uploaded as part of a post.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommender_video_entry', to='api.post'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Video file, primarily for videos not sourced from a Post. If source_post is set, this may be redundant.', null=True, upload_to='recommender_internal_videos/'),
        ),
    ]
