# Generated by Django 5.2.1 on 2025-06-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_video_source_post_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideointeraction',
            name='commented',
            field=models.BooleanField(default=False, help_text='Did the user comment on this video?'),
        ),
    ]
