# Generated by Django 5.2.1 on 2025-06-07 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_post_view_count_post_watch_time_comment'),
        ('recommender', '0004_uservideointeraction_commented'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=100)),
                ('interaction_type', models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('view', 'View'), ('watch', 'Watch'), ('search', 'Search')], max_length=20)),
                ('interaction_score', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keyword_interactions', to='api.post')),
                ('source_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keyword_interactions', to='recommender.video')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Keyword Activity',
                'verbose_name_plural': 'User Keyword Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserInterestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords_summary', models.JSONField(blank=True, default=dict, help_text="Summary of user's keyword interests, e.g., scores, timestamps.")),
                ('interest_embedding', models.JSONField(blank=True, help_text='Placeholder for user interest embedding vector.', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Timestamp when this profile was last updated.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interest_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Interest Profile',
                'verbose_name_plural': 'User Interest Profiles',
                'ordering': ['-last_updated'],
            },
        ),
    ]
