# Generated by Django 5.2.1 on 2025-06-05 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('media_file', models.FileField(upload_to='ads_media/')),
                ('target_url', models.URLField(max_length=2000)),
                ('ad_copy', models.TextField()),
                ('button_text', models.CharField(choices=[('visit', 'Visit'), ('shop', 'Shop'), ('contact_us', 'Contact Us'), ('learn_more', 'Learn More'), ('sign_up', 'Sign Up')], max_length=20)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords for targeting')),
                ('target_age_min', models.PositiveIntegerField(blank=True, null=True)),
                ('target_age_max', models.PositiveIntegerField(blank=True, null=True)),
                ('target_gender', models.CharField(blank=True, choices=[('any', 'Any'), ('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary')], default='any', max_length=10, null=True)),
                ('target_device', models.CharField(blank=True, choices=[('any', 'Any'), ('mobile', 'Mobile'), ('desktop', 'Desktop')], default='any', max_length=10, null=True)),
                ('target_time_of_day_start', models.TimeField(blank=True, null=True)),
                ('target_time_of_day_end', models.TimeField(blank=True, null=True)),
                ('target_region', models.CharField(blank=True, help_text='e.g., city, state, country', max_length=255, null=True)),
                ('budget', models.DecimalField(decimal_places=2, help_text='Minimum $10.00', max_digits=10)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('live', 'Live'), ('paused', 'Paused'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending_review', max_length=20)),
                ('stripe_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ad',
                'verbose_name_plural': 'Ads',
                'ordering': ['-created_at'],
            },
        ),
    ]
