# Generated by Django 5.2.1 on 2025-06-06 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='clicks',
            field=models.IntegerField(default=0, help_text='Total times the ad has been clicked.'),
        ),
        migrations.AddField(
            model_name='ad',
            name='impressions',
            field=models.IntegerField(default=0, help_text='Total times the ad has been viewed.'),
        ),
        migrations.AddField(
            model_name='ad',
            name='keyword_processed_data',
            field=models.JSONField(blank=True, help_text='Processed keyword data, e.g., list of tokens or placeholder for embeddings.', null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('pending_approval', 'Pending Approval'), ('live', 'Live'), ('paused', 'Paused'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending_review', max_length=20),
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_clicks', to='ads.ad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_clicks_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-click_time'],
            },
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impression_time', models.DateTimeField(auto_now_add=True)),
                ('impression_date', models.DateField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_impressions', to='ads.ad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_impressions_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-impression_time'],
                'unique_together': {('ad', 'user', 'impression_date')},
            },
        ),
    ]
