# Generated by Django 5.2.1 on 2025-06-06 00:35

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad_clicks_ad_impressions_ad_keyword_processed_data_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE "ads_ad" ALTER COLUMN "target_time_of_day_start" TYPE timestamp with time zone
            USING (DATE_TRUNC('day', NOW()) + "target_time_of_day_start");
            """,
            reverse_sql="""
            ALTER TABLE "ads_ad" ALTER COLUMN "target_time_of_day_start" TYPE time without time zone;
            """
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE "ads_ad" ALTER COLUMN "target_time_of_day_end" TYPE timestamp with time zone
            USING (DATE_TRUNC('day', NOW()) + "target_time_of_day_end");
            """,
            reverse_sql="""
            ALTER TABLE "ads_ad" ALTER COLUMN "target_time_of_day_end" TYPE time without time zone;
            """
        ),
        migrations.AlterField(
            model_name='ad',
            name='target_time_of_day_start',
            field=models.DateTimeField(blank=True, help_text='Targeting start date and time', null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='target_time_of_day_end',
            field=models.DateTimeField(blank=True, help_text='Targeting end date and time', null=True),
        ),
    ]


